name: Build, Test, Publish

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and run tests
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory:TestResults --logger:trx

  publish:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish ./src/Presentations/Samples.ModularMonolith.Presentation.BootstrapperApi/Samples.ModularMonolith.Presentation.BootstrapperApi.csproj

      - name: Zip source code
        run: zip -r sample.modularmonolith.source-code.zip ./src

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: TestResults/*.trx

      - name: Publish source code zip
        uses: actions/upload-artifact@v2
        with:
          name: source-code-zip
          path: sample.modularmonolith.source-code.zip
